CREATE TABLE IF NOT EXISTS `poli_gigi_rujukan` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `no_rm` VARCHAR(255) NOT NULL,
  `tempat_lahir` VARCHAR(255) NOT NULL,
  `tanggal_lahir` DATE NOT NULL,
  `umur` INT NOT NULL,
  `alamat` VARCHAR(255) NOT NULL,
  `petugas_pel` VARCHAR(255) NOT NULL,
  `pemberi_info` VARCHAR(255) NOT NULL,
  `penerima_info` VARCHAR(255) NOT NULL,
  `diagnosis` VARCHAR(255) DEFAULT NULL,
  `nama_tujuan_tindakan` VARCHAR(255) DEFAULT NULL,
  `indikasi_tindakan` VARCHAR(255) DEFAULT NULL,
  `tata_cara` VARCHAR(255) DEFAULT NULL,
  `risiko_komplikasi` VARCHAR(255) DEFAULT NULL,
  `prognosis` VARCHAR(255) DEFAULT NULL,
  `alternatif_risiko` VARCHAR(255) DEFAULT NULL,
  `biaya_tindakan` VARCHAR(255) DEFAULT NULL,
  `signature1` TEXT DEFAULT NULL,
  `signature2` TEXT DEFAULT NULL,
  `nama_sign` VARCHAR(255) NOT NULL,
  `umur_sign` INT NOT NULL,
  `jenis_kelamin` VARCHAR(20) NOT NULL,
  `alamat_sign` VARCHAR(255) NOT NULL,
  `tanggal` DATE NOT NULL,
  `jam` TIME NOT NULL,
  `persetujuan_tindakan` VARCHAR(50) NOT NULL,
  `created_at` DATETIME DEFAULT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  `signature3` TEXT DEFAULT NULL,
  `signature4` TEXT DEFAULT NULL,
  `signature5` TEXT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
